{
 "title": "NB-IoT e2e",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "online e2e devices",
   "type": "singlestat",
   "description": "The number of e2e devices",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nbiot_e2e_up) / ignoring(instance, job) nbiot_e2e_device_count"
    }
   ]
  },
  {
   "title": "Devices up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nbiot_e2e_up", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Received packets (5 min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nbiot_e2e_received_messages_total[5m])",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Dropped packets (5 min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nbiot_e2e_dropped_packets_total[1m])",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "nbiot-e2e git hash",
   "type": "graph",
   "description": "The hash of the last git commit for the nbiot-e2e repository when building the device",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (git_hash) (nbiot_e2e_build_info)",
     "legendFormat": "{{git_hash}}"
    }
   ]
  },
  {
   "title": "ArduinoNBIoT git hash",
   "type": "graph",
   "description": "The hash of the last git commit for the ArduinoNBIoT library when building the device",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (git_hash) (nbiot_e2e_arduino_build_info)",
     "legendFormat": "{{git_hash}}"
    }
   ]
  }
 ]
}